---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: "hacbs-signing-pipeline"
    app: "hacbs-signing-pipeline"
    env: stage
    paas.redhat.com/appcode: RSIG-001
  name: "hacbs-signing-pipeline-config-staging-openshifthosted"
data:
  PYXIS_URL: "https://pyxis.stage.engineering.redhat.com"
  SIG_KEY_ID: "4096R/37036783 SHA-256"
  SIG_KEY_NAME: "redhate2etesting"
  SSL_CERT_FILE_NAME: "hacbs-signing-pipeline.pem"
  SSL_CERT_SECRET_NAME: "hacbs-signing-pipeline-staging-certs"
  SSL_KEY_FILE_NAME: "hacbs-signing-pipeline.key"
  PYXIS_SSL_CERT_FILE_NAME: "hacbs-signing-pipeline.pem"
  PYXIS_SSL_CERT_SECRET_NAME: "hacbs-signing-pipeline-staging-certs"
  PYXIS_SSL_KEY_FILE_NAME: "hacbs-signing-pipeline.key"
  UMB_SSL_CERT_FILE_NAME: "hacbs-signing-pipeline.pem"
  UMB_SSL_CERT_SECRET_NAME: "hacbs-signing-pipeline-staging-certs"
  UMB_SSL_KEY_FILE_NAME: "hacbs-signing-pipeline.key"
  UMB_CLIENT_NAME: "hacbs-signing-pipeline-nonprod"
  UMB_URL: "umb.stage.api.redhat.com"
  UMB_LISTEN_TOPIC: VirtualTopic.eng.robosignatory.hacbs.sign
  UMB_PUBLISH_TOPIC: VirtualTopic.eng.hacbs-signing-pipeline.hacbs.sign
